/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1acc86ae9f51c72bee10f9a045cb80ae)
interface __BaseEnv_Env {
	ARTIFACTS_BUCKET: R2Bucket;
	LOADER: WorkerLoader;
	AI: Ai;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	GuildMemory: DurableObjectNamespace<import("./src/server").GuildMemoryObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "GuildMemoryObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
