/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --env-file /private/tmp/sturm-empty.env` (hash: ffb37383f6b05adf4b9c55592c76829e)
interface __BaseEnv_Env {
	ARTIFACTS_BUCKET: R2Bucket;
	LOADER: WorkerLoader;
	BROWSER: BrowserRun;
	AI: Ai;
	IMAGES: ImagesBinding;
	ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
	GuildMemory: DurableObjectNamespace<import("./src/server").GuildMemoryObject>;
	DiscordRest: DurableObjectNamespace<import("./src/server").DiscordRestDispatcher>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent" | "GuildMemoryObject" | "DiscordRestDispatcher";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
